{
  "contest": 226,
  "handle": "Trust_me_bro",
  "risk": "2",
  "title": "Potential Reentrancy Attack in withdraw() Function",
  "issueId": 347,
  "issueUrl": "https://github.com/code-423n4/2023-03-asymmetry-findings/issues/347"
}